'use strict';
(() => {
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
  const current=()=>/^(?:0\.11\.|0\.12\.)/.test(String(document.documentElement.dataset.releaseUi||document.documentElement.dataset.remoteUi||''));
  const STATE_KEY='crowd_orbit_ui_state_v1';
  const SHARE_KEY='crowd_orbit_share_inbox_v1';
  const SCAN_KEY='crowd_orbit_auto_scan_pending_v1';
  const VIEWS=new Set(['orbit','radar','people','campaigns','collect','settings']);
  const MAX_STATE_AGE=24*60*60*1000;
  const supported=/^https:\/\/(?:[^/]+\.)?(?:instagram\.com|tiktok\.com|x\.com|twitter\.com|youtube\.com|youtu\.be|soundcloud\.com|linkedin\.com|spotify\.com)(?:\/|$)/i;
  let readySent=false,raf=0,restoreDone=false,saveTimer=0,scanInstalled=false;
  const scans=new Map();

  function ensureZones(stage){
    stage.querySelectorAll('.co70-ring,.co70-axis,.co73-zone-labels,.co74-zones,.co90-orbit-halo,.co73-you').forEach(el=>el.remove());
    if(stage.querySelector('.co80-zones'))return;
    const zones=document.createElement('div');zones.className='co80-zones';zones.setAttribute('aria-hidden','true');
    zones.innerHTML='<div class="co80-zone outer"><span><b>DISCOVERY</b><small>new / unproven</small></span></div><div class="co80-zone active"><span><b>ACTIVE SIGNAL</b><small>useful opportunity</small></span></div><div class="co80-zone inner"><span><b>INNER ORBIT</b><small>strong relationship</small></span></div>';
    stage.prepend(zones);
  }
  function place(nodes,rx,ry,phase,zone){nodes.sort((a,b)=>Number(a.dataset.person||0)-Number(b.dataset.person||0));const total=nodes.length;if(!total)return;nodes.forEach((node,index)=>{const angle=(phase+(index*360/total))*Math.PI/180;node.style.left=`${(50+Math.cos(angle)*rx).toFixed(2)}%`;node.style.top=`${(50+Math.sin(angle)*ry).toFixed(2)}%`;node.dataset.orbitZone=zone})}
  function markReady(){const app=$('#co70-app');if(!app||readySent)return;readySent=true;app.classList.add('co111-ready');requestAnimationFrame(()=>requestAnimationFrame(()=>{try{window.CrowdOrbitNative?.interfaceReady?.()}catch{}window.dispatchEvent(new CustomEvent('crowdorbitinterfaceready',{detail:{version:String(document.documentElement.dataset.releaseUi||document.documentElement.dataset.remoteUi||'0.12.1')}}))}))}
  function layout(){if(!current())return;const stage=$('#co70-app .co70-orbit-stage');if(!stage){markReady();return}ensureZones(stage);const nodes=$$('.co70-node',stage),groups={warm:[],priority:[],ready:[],new:[]};nodes.forEach(node=>groups[node.classList.contains('warm')?'warm':node.classList.contains('priority')?'priority':node.classList.contains('ready')?'ready':'new'].push(node));place(groups.warm,16,12,-90,'inner');place(groups.priority,27,20,-38,'priority');place(groups.ready,36,28,18,'active');place(groups.new,44,35,-10,'discovery');stage.classList.add('co111-laid-out');markReady()}

  function readState(){try{return JSON.parse(localStorage.getItem(STATE_KEY)||'{}')||{}}catch{return{}}}
  function activeView(){return $('#co70-app .co70-nav button.active')?.dataset.nav||$('#co70-app .co70-view.active')?.dataset.view||'orbit'}
  function pendingShare(){try{if(localStorage.getItem(SHARE_KEY)||localStorage.getItem(SCAN_KEY))return true;const p=new URLSearchParams(location.search);return ['share','text','share_url','url','title','subject'].some(k=>Boolean(p.get(k)))}catch{return false}}
  function captureState(){if(!current()||!$('#co70-app'))return;const old=readState(),view=activeView(),scroll=old.scroll&&typeof old.scroll==='object'?old.scroll:{};scroll[view]=Math.max(0,Math.round(window.scrollY||document.documentElement.scrollTop||0));const draft=$('#co70-paste'),person=$('#co80-person.open [data-delete-id]');const next={...old,view,scroll,at:Date.now(),personId:person?Number(person.dataset.deleteId||0):0};if(draft)next.collectDraft=draft.value;try{localStorage.setItem(STATE_KEY,JSON.stringify(next))}catch{}}
  function queueCapture(delay=90){clearTimeout(saveTimer);saveTimer=setTimeout(captureState,delay)}
  function restoreState(){if(restoreDone||!current())return;const app=$('#co70-app');if(!app)return;const saved=readState();if(!saved.at||Date.now()-Number(saved.at)>MAX_STATE_AGE){restoreDone=true;return}restoreDone=true;if(pendingShare())return;const wanted=VIEWS.has(saved.view)?saved.view:'orbit';setTimeout(()=>{const nav=$(`#co70-app .co70-nav [data-nav="${wanted}"]`);if(nav&&activeView()!==wanted)nav.click();setTimeout(()=>{if(pendingShare())return;const draft=$('#co70-paste');if(draft&&saved.collectDraft&&!draft.value){draft.value=String(saved.collectDraft);draft.dispatchEvent(new Event('input',{bubbles:true}))}const y=Number(saved.scroll?.[wanted]);if(Number.isFinite(y)&&y>0)window.scrollTo(0,y);const personId=Number(saved.personId||0);if(personId&&window.CrowdOrbit080?.openPerson)window.CrowdOrbit080.openPerson(personId)},420)},120)}

  const text=v=>String(v??'').trim();
  function normaliseShare(raw){let value=raw;if(typeof value==='string'){try{const parsed=JSON.parse(value);value=parsed&&typeof parsed==='object'?parsed:{text:value}}catch{value={text:value}}}value=value&&typeof value==='object'?value:{};return {text:text(value.text||value.share||value.share_url||value.url),title:text(value.title||value.subject)}}
  function profileUrl(payload){const all=[payload.text,payload.title].filter(Boolean).join('\n');for(const match of all.match(/https:\/\/[^\s<>"']+/ig)||[]){const clean=match.replace(/[),.;!?\]}]+$/,'');if(supported.test(clean))return clean}return''}
  function cleanShare(payload){return [payload.title,payload.text].filter(Boolean).join('\n').split(/\r?\n/).map(text).filter(Boolean).filter(line=>!/^(?:instagram|tiktok|twitter|x|youtube|linkedin|soundcloud|spotify)\s+share$/i.test(line)&&!/^share(?:d)?\s+(?:a\s+)?profile$/i.test(line)).join('\n')}
  function goCollect(message){const nav=$('#co70-app .co70-nav [data-nav="collect"]');if(nav&&!nav.classList.contains('active'))nav.click();setTimeout(()=>{const status=$('#co70-collect-result');if(status){status.className='co70-status';status.textContent=message}const preview=$('#co110-preview');if(preview&&!preview.children.length)preview.innerHTML='<div class="co110-empty"><strong>Scanning public profile…</strong><p>Crowd Orbit is checking visible profile text, public metadata, audience and other evidence before analysis.</p></div>'},120)}
  function clearScan(){try{localStorage.removeItem(SCAN_KEY)}catch{}}
  function startScan(payload,original){const url=profileUrl(payload);if(!url||!window.CrowdOrbitNative?.scanPublicProfile)return original.receive(payload);const id='scan-'+Date.now()+'-'+Math.random().toString(36).slice(2,8),item={id,url,payload,at:Date.now()};scans.set(id,{...item,original});try{localStorage.setItem(SCAN_KEY,JSON.stringify(item))}catch{}goCollect('Scanning the shared public profile automatically…');try{window.CrowdOrbitNative.scanPublicProfile(url,id);return true}catch{scans.delete(id);clearScan();return original.receive(payload)}}
  function receiveScan(id,raw){let result={};try{result=typeof raw==='string'?JSON.parse(raw):raw||{}}catch{}let job=scans.get(id);if(!job){try{const saved=JSON.parse(localStorage.getItem(SCAN_KEY)||'null');if(saved&&saved.id===id)job={...saved,original:window.__CrowdOrbitShareOriginal}}catch{}}if(!job||!job.original)return false;scans.delete(id);clearScan();const base=cleanShare(job.payload);if(result.ok&&text(result.scanText)){const enriched=[text(result.scanText),base,job.url].filter(Boolean).join('\n');goCollect(`Public ${text(result.platform)||'profile'} scan complete. Analysing the evidence…`);return job.original.receive({text:enriched,title:''})}const fallback={text:[base,job.url].filter(Boolean).join('\n'),title:''};const ok=job.original.receive(fallback);setTimeout(()=>{const status=$('#co70-collect-result');if(status){status.className='co70-status error';status.textContent='The profile was shared successfully, but Crowd Orbit could not read enough visible or public profile evidence. The profile route has been kept for review.'}},250);return ok}
  function installScanner(){if(scanInstalled||!current())return;const original=window.CrowdOrbitShare;if(!original||typeof original.receive!=='function'){setTimeout(installScanner,80);return}scanInstalled=true;window.__CrowdOrbitShareOriginal=original;window.CrowdOrbitShare={...original,receive(raw){return startScan(normaliseShare(raw),original)}};try{const saved=JSON.parse(localStorage.getItem(SCAN_KEY)||'null');if(saved&&saved.url&&Date.now()-Number(saved.at||0)<120000&&window.CrowdOrbitNative?.scanPublicProfile){scans.set(saved.id,{...saved,original});goCollect('Resuming automatic public profile scan…');window.CrowdOrbitNative.scanPublicProfile(saved.url,saved.id)}else if(saved)clearScan()}catch{clearScan()}}
  window.CrowdOrbitProfileScan={receive:receiveScan};

  function scanEnabled(){try{return Boolean(window.CrowdOrbitNative?.isVisibleProfileScanEnabled?.())}catch{return false}}
  function setupCard(){
    if(!String(window.CrowdOrbitNative?.getShellVersion?.()||'').startsWith('0.5.6'))return;
    const root=$('#co70-settings');if(!root)return;
    let card=$('#co121-visible-scan',root);
    if(!card){card=document.createElement('article');card.id='co121-visible-scan';card.className='co70-card co70-panel';card.style.marginTop='14px';card.innerHTML='<div class="co70-card-head"><div><span class="co70-eyebrow">VISIBLE PROFILE SCAN</span><h3>Read the profile details you can actually see</h3></div><span class="co70-pill" id="co121-state">CHECKING</span></div><p class="co70-sub" style="margin-top:10px">When enabled, Crowd Orbit temporarily reads visible text from supported social profile screens on this device, then merges it with the shared profile URL and public metadata. The snapshot stays local and is cleared after the share is processed.</p><div class="co70-actions" style="margin-top:14px"><button class="co70-btn gold" id="co121-enable">Enable Visible Profile Scan</button><button class="co70-btn ghost" id="co121-refresh">Refresh status</button></div><div class="co70-status" id="co121-help"></div>';root.appendChild(card);$('#co121-enable',card).onclick=()=>{try{window.CrowdOrbitNative?.openVisibleProfileScanSettings?.()}catch{}};$('#co121-refresh',card).onclick=setupCard}
    const on=scanEnabled(),state=$('#co121-state',card),button=$('#co121-enable',card),help=$('#co121-help',card);if(state)state.textContent=on?'ON':'OFF';if(button)button.textContent=on?'Visible Profile Scan enabled':'Enable Visible Profile Scan';if(help){help.className='co70-status'+(on?'':' error');help.textContent=on?'Ready. Leave the visible profile name, bio and follower area on screen, then Share → Crowd Orbit.':'One-time setup required: tap Enable, find Crowd Orbit in Android Accessibility settings and switch it on. Return here afterwards.'}
  }

  const schedule=()=>{cancelAnimationFrame(raf);raf=requestAnimationFrame(()=>{layout();restoreState();installScanner();setupCard()})};
  new MutationObserver(()=>{schedule();if(restoreDone)queueCapture(160)}).observe(document.documentElement,{subtree:true,childList:true});
  window.addEventListener('resize',schedule,{passive:true});window.addEventListener('scroll',()=>queueCapture(180),{passive:true});
  document.addEventListener('pointerdown',e=>{if(e.target.closest?.('#co70-app .co70-nav [data-nav]'))captureState()},true);document.addEventListener('click',e=>{if(e.target.closest?.('#co70-app .co70-nav [data-nav]'))queueCapture(180)},false);document.addEventListener('input',e=>{if(e.target?.id==='co70-paste')queueCapture(120)},true);
  document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')captureState();else{restoreState();schedule()}});window.addEventListener('pagehide',captureState);window.addEventListener('blur',captureState);window.addEventListener('pageshow',()=>{restoreState();schedule()});window.addEventListener('focus',()=>{restoreState();schedule()});
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',schedule,{once:true});else schedule();
  window.CrowdOrbit111={layout,captureState,restoreState,setupCard};
})();
